runtime: nodejs12

env_variables:
  APP_ENV: production
  MONGO_URL: {secret:MONGO_URL}
  ACCESS_TOKEN_SECRET: {secret:ACCESS_TOKEN_SECRET}
  REFRESH_TOKEN_SECRET: {secret:REFRESH_TOKEN_SECRET}
  ACCESS_TOKEN_EXPIRATION_DURATION: '15m'
  REFRESH_EXPIRATION_DURATION: '180d'

