import { enumerate } from '@utils/enumerate';

import { ConfigKeys } from './types';

export const CONFIG_KEYS = enumerate<ConfigKeys>([
  'APP_ENV',
  'PORT',
  'APP_URL',

  'MONGO_URL',
  'TESTING_EMAIL',

  'ACCESS_TOKEN_SECRET',
  'REFRESH_TOKEN_SECRET',
  'RESET_TOKEN_SECRET',
  'ACCESS_TOKEN_EXPIRATION_DURATION',
  'REFRESH_EXPIRATION_DURATION',
  'RESET_TOKEN_EXPIRATION_DURATION',

  'ADMIN_ACCESS_TOKEN_SECRET',
  'ADMIN_ACCESS_TOKEN_EXPIRATION_DURATION',
  'ADMIN_REFRESH_TOKEN_SECRET',
  'ADMIN_REFRESH_EXPIRATION_DURATION',

  'SMAP_API_URL',
  'SERVICE_LENGTH_CHUNK_SIZE_IN_MINUTES',

  'GMAIL_EMAIL',
  'GMAIL_APP_PASSWORD',
]);
